config/routes.rb
Rails.application.routes.draw do
  resources :first_words
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "first_words#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/first_word.rb
class FirstWord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/first_words_controller.rb
class FirstWordsController < ApplicationController
  before_action :set_first_word, only: %i[ show edit update destroy ]

  # GET /first_words or /first_words.json
  def index
    @first_words = FirstWord.all
    @first_word = FirstWord.new
  end

  # GET /first_words/1 or /first_words/1.json
  def show
  end

  # GET /first_words/new
  def new
    @first_word = FirstWord.new
  end

  # GET /first_words/1/edit
  def edit
  end

  # POST /first_words or /first_words.json
  def create
    @first_word = FirstWord.new(first_word_params)

    respond_to do |format|
      if @first_word.save
        format.html { redirect_to first_words_url, notice: "First word was successfully created." }
        format.json { render :show, status: :created, location: @first_word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @first_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_words/1 or /first_words/1.json
  def update
    respond_to do |format|
      if @first_word.update(first_word_params)
        format.html { redirect_to first_word_url(@first_word), notice: "First word was successfully updated." }
        format.json { render :show, status: :ok, location: @first_word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @first_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_words/1 or /first_words/1.json
  def destroy
    @first_word.destroy!

    respond_to do |format|
      format.html { redirect_to first_words_url, notice: "First word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_word
      @first_word = FirstWord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def first_word_params
      params.require(:first_word).permit(:word, :language, :firstCharacter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_words_helper.rb
module FirstWordsHelper
end

app/views/first_words/_first_word.html.erb
<div id="<%= dom_id first_word %>" class="bg-gray-100 p-4 my-4 rounded-md">
  <p>
    <%= first_word.word %>
  </p>

  <p class="text-gray-500 text-sm">
    <%= first_word.language %>
  </p>

  <p class="text-gray-500 text-sm bg-gray-200 p-2 rounded-xl">
    <%= first_word.firstCharacter %>
  </p>

</div>

app/views/first_words/_form.html.erb
<%= form_with(model: first_word) do |form| %>
  <% if first_word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(first_word.errors.count, "error") %> prohibited this first_word from being saved:</h2>

      <ul>
        <% first_word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, style: "display: block" %>
    <%= form.text_field :word, id: "word_input" %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%# form for selecting options %>
    <%= form.select :language, ["English", "German", "French", "Spanish", "Italian", "Portuguese", "Dutch", "Russian", "Japanese", "Chinese", "Korean", "Arabic", "Hindi"] %>
  </div>

  <div>
    <%= form.label :firstCharacter, style: "display: block" %>
    <%= form.text_field :firstCharacter, id: "firstCharacter_input" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/first_words/edit.html.erb
<h1>Editing first word</h1>

<%= render "form", first_word: @first_word %>

<br>

<div>
  <%= link_to "Show this first word", @first_word %> |
  <%= link_to "Back to first words", first_words_path %>
</div>

app/views/first_words/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="font-bold text-3xl text-center m-4 p-4"
>First words list
</h1>
<div id="first_words" class="flex flex-wrap justify-center space-x-4">
  <% @first_words.each do |first_word|  %>
    <div class="relative">
      <%= render first_word %>
      <div class="absolute top-3 right-0 bg-white rounded-full hover:bg-slate-500">
        <%= button_to 'X', first_word, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold size-6 rounded" %>
      </div>
    </div>
  <% end %>
</div>

<div class="h-4 hover:bg-slate-800 bg-slate-400 w-5/6 m-auto rounded-lg"></div>
<br>

<div class="m-4">
  <%= render "form", first_word: @first_word %>
</div>


<%= link_to "New first word", new_first_word_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
<div class="">
  <h2 class="font-bold text-3xl text-center m-4 p-4">
    this is text a
  </h2>
</div>


<script>

const wordInput = document.getElementById("word_input");
console.log("wordInput: ", wordInput);
wordInput.focus();  // Focus on the word input after page loads or reloads



</script>

app/views/first_words/new.html.erb
<h1>New first word</h1>

<%= render "form", first_word: @first_word %>

<br>

<div>
  <%= link_to "Back to first words", first_words_path %>
</div>

app/views/first_words/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @first_word %>

<div>
  <%= link_to "Edit this first word", edit_first_word_path(@first_word) %> |
  <%= link_to "Back to first words", first_words_path %>

  <%= button_to "Destroy this first word", @first_word, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LanguagePatternDatabaseRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="m-4 sm:container border-2 border-gray-400 rounded-lg sm:mx-auto p-4">
      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>